forge "http://forge.puppetlabs.com"

mod 'puppetlabs-acl', '3.2.1'
mod 'puppetlabs-chocolatey', '5.2.0'
mod 'puppetlabs-stdlib', '6.5.0'
mod 'puppetlabs-powershell', '4.1.0'
mod 'puppetlabs-pwshlib', '0.6.3'
mod 'puppetlabs-registry', '3.2.0'
