forge "http://forge.puppetlabs.com"
#
# I want to download some modules to check if r10k feature in Onceover works correctly.
#

# Modules from Git
# Examples: https://github.com/puppetlabs/r10k/blob/master/doc/puppetfile.mkd#examples
mod 'apache',
 :git    => 'https://github.com/puppetlabs/puppetlabs-apache',
 :commit => '83401079053dca11d61945bd9beef9ecf7576cbf'

#mod 'apache',
#  :git    => 'https://github.com/puppetlabs/puppetlabs-apache',
#  :branch => 'docs_experiment'

# Dependencies
mod 'puppetlabs-stdlib', :latest

mod 'puppetlabs/provision',
  git: 'https://github.com/dylanratcliffe/provision.git',
  branch: 'vagrant_dir_fix'

mod 'facts',
  :git => 'git://github.com/puppetlabs/puppetlabs-facts.git'

mod 'puppet_agent',
  :git => 'git://github.com/puppetlabs/puppetlabs-puppet_agent.git'

mod 'puppetlabs-package', :latest
mod 'puppetlabs-exec', :latest

# Debugging
mod 'nwops-debug', :latest
