# Dependencies
mod 'puppetlabs-stdlib', :latest

mod 'puppetlabs/provision',
  git: 'https://github.com/dylanratcliffe/provision.git',
  branch: 'return_node_object'

mod 'facts',
  :git => 'git://github.com/puppetlabs/puppetlabs-facts.git'

mod 'puppet_agent',
  :git => 'git://github.com/puppetlabs/puppetlabs-puppet_agent.git'

mod 'puppetlabs-package', :latest
mod 'puppetlabs-exec', :latest

# Debugging
mod 'nwops-debug', :latest