forge "http://forge.puppetlabs.com"
#
# I want to download some modules to check if r10k feature in Onceover works correctly.
#

# Versions should be updated to be the latest at the time you start
mod "puppetlabs/stdlib",      '6.5.0'

# Modules from Git
# Examples: https://github.com/puppetlabs/r10k/blob/master/doc/puppetfile.mkd#examples
mod 'apache',
 :git    => 'https://github.com/puppetlabs/puppetlabs-apache',
 :commit => '83401079053dca11d61945bd9beef9ecf7576cbf'

#mod 'apache',
#  :git    => 'https://github.com/puppetlabs/puppetlabs-apache',
#  :branch => 'docs_experiment'
