name: Publish Gem

on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
      - uses: fregante/setup-git-user@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.3
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      - name: Release Gem
        uses: cadwallion/publish-rubygems-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RUBYGEMS_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}
          RELEASE_COMMAND: bundle exec rake release